### ISSUE TITLE
Corrección compañero.

### ISSUE THREAD

**Issue by mortega87** [mortega87/ProyectoCC-16-17#15]

**Comment by jmanday** [comment]
He probado el fichero Vagrantfile y la orquestación de las máquinas virtuales se ha echo correctamente como se muestra en las imágenes:

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img1corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img2corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img3corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img4corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img5corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img6corr.png)
![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito3/h3-img7corr.png)

**Comment by mortega87** [comment]
Gracias @jmanday , he corregido también tu oquestación.
