### ISSUE TITLE
Corrección compañero

### ISSUE THREAD

**Issue by mortega87** [mortega87/ProyectoCC-16-17#21]

**Comment by mortega87** [comment]
He corregido el hito 4 de @jmanday. Como podemos ver en las siguientes imágenes todo ha funcionado correctamente.

1. Creación de primer contenedor para mongo.
![](https://rawgit.com/mortega87/Images/master/dockerjmanday1.png)

2. Ejecución del contenedor.
![](https://rawgit.com/mortega87/Images/master/dockerjmanday2.png)

3. Creación de imagen a través de Dockerfile.
![](https://rawgit.com/mortega87/Images/master/dockerjmanday3.png)

4. Vemos que la imagen se ha creado correctamente.
![](https://rawgit.com/mortega87/Images/master/dockerjmanday4.png)

**Comment by jmanday** [comment]
He seguido los pasos indicados Mario para la realización del hito y he podido comprobar que el funcionamiento es el correcto como se muestran en las imágenes:

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img19.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img20.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img21.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img22.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img23.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img24.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img25.png)
